baseURL = "https://teralis.bangunan.co/"
languageCode = "id"
title = "Teralis dan Pagar Besi | Pasang Teralis dan Pagar Besi Minimalis Berpengalaman"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Tukang Pasang Teralis dan Pagar Besi - Borongan Pemasangan Teralis dan Pagar Besi Minimalis Modern dengan harga terjangkau dan kualitas terbaik."
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jasa pasang teralis", "teralis besi", "pagar besi minimalis", "tukang teralis berpengalaman", "pagar besi modern", "pagar rumah minimalis"]
  base_price = 3000000
  price_range = 500000
  free_consultation = true
  service_types = [
  "Pemasangan Teralis Jendela",
  "Pemasangan Pagar Besi",
  "Pembuatan Teralis Custom",
  "Pemasangan Pagar Besi Minimalis",
  "Perbaikan Teralis dan Pagar"
  ]
  categories = ["Jasa Pemasangan Teralis", "Tukang Pagar Besi", "Teralis dan Pagar"]
  payment_methods = ["Bayar Bertahap", "Transfer Bank", "Bayar DP 50%", "Transfer Setelah Selesai"]
  cancellation_policies = [
  "Layanan dapat dibatalkan jika tidak sesuai dengan kesepakatan.",
  "Pengembalian biaya dapat dilakukan jika hasil pekerjaan tidak memuaskan.",
  "Revisi gratis untuk hasil pemasangan yang tidak sesuai."
  ]
  area_served = ["Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Cikarang", "Karawang", "Subang", "Cikampek", "Purwakarta", "Rangkas Bitung", "Serang"]
  service_output = "Bangunan dengan teralis atau pagar besi yang terpasang sesuai permintaan"

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Pasang Teralis dan Pagar Besi Berkualitas"
  hero_description = "Kami menawarkan layanan borongan pemasangan teralis dan pagar besi minimalis modern dengan harga terjangkau dan kualitas terbaik. Solusi ideal untuk keamanan dan tampilan elegan bangunan Anda dengan bahan besi yang kuat dan tahan lama."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Teralis & Pagar"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan layanan pemasangan teralis dan pagar besi minimalis modern dengan kualitas unggul, harga bersaing, dan layanan profesional. Gratis konsultasi untuk membantu Anda memilih desain teralis dan pagar yang tepat untuk proyek Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "teralis.bangunan.co menawarkan layanan pemasangan teralis dan pagar besi dengan harga yang kompetitif. Kami mengutamakan kepuasan pelanggan melalui hasil kerja yang rapi, cepat, serta material besi yang kuat dan tahan lama. Pilih kami untuk mempercantik sekaligus melindungi bangunan Anda dengan teralis dan pagar berkualitas."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Andi|Joko|Eko|Rudi|Agus|Fajar|Dedi|Hendra|Samsul}"
  message = "{Saya {menggunakan|memanfaatkan|memakai} layanan {pemasangan teralis|instalasi teralis} dari teralis.bangunan.co untuk {rumah|hunian} saya. Hasilnya {sangat rapi|benar-benar rapi|memuaskan} dan kualitasnya {luar biasa|sangat baik|hebat}|Saya {memanfaatkan|menggunakan|memakai} layanan {pemasangan teralis|instalasi teralis} dari teralis.bangunan.co untuk {rumah|hunian} saya. Hasilnya {sangat memuaskan|benar-benar memuaskan|memuaskan sekali} dan kualitasnya {luar biasa|sangat baik|hebat}}."
  response = "{Terima kasih atas {kepercayaan|kepercayaan Anda}! Kami {senang|gembira|bahagia} dapat menyediakan teralis {berkualitas|yang berkualitas} untuk {rumah|hunian} Anda|Kami menghargai {kepercayaan|kepercayaan Anda}! Senang bisa menyediakan teralis {berkualitas|yang berkualitas} untuk {rumah|hunian} Anda.}"
  rating = 4.5

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Ayu|Dewi|Lina|Maya|Putri|Ratna|Nina|Ika}"
  message = "{teralis.bangunan.co {sangat membantu|benar-benar membantu|membantu sekali} saya dalam {memilih|menggali|mencari} dan {memasang|melakukan pemasangan} pagar besi yang {sesuai|cocok} dengan {kebutuhan|keperluan} rumah saya. Pelayanannya {sangat memuaskan|benar-benar memuaskan|memuaskan sekali}|teralis.bangunan.co {benar-benar membantu|sangat membantu|bantu sekali} saya dalam {memilih|mencari|menggali} dan {memasang|melakukan pemasangan} pagar besi yang {tepat|cocok} untuk {rumah|hunian} saya. Pelayanannya {sangat memuaskan|benar-benar memuaskan|memuaskan sekali}}."
  response = "{Kami {sangat|amat} menghargai ulasan Anda. Senang mendengar bahwa Anda {puas|senang|terkesan} dengan pagar besi dari kami|Kami menghargai {feedback|ulasannya}. Senang mengetahui Anda {puas|senang|terkesan} dengan pagar besi yang kami sediakan.}"
  rating = 4.8

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Budi|Eko|Rudi|Agus|Fajar|Dedi|Hendra|Samsul|Andi}"
  message = "{Pagar besi dari teralis.bangunan.co {sangat cocok|cocok sekali|tepat} untuk proyek ruko saya. Pemasangannya {cepat|lancar|efisien} dan hasilnya {memuaskan|sangat memuaskan|baik}|Pagar besi yang saya beli dari teralis.bangunan.co {sangat sesuai|cocok|tepat} untuk proyek ruko saya. Pemasangannya {cepat|lancar|efisien} dan hasilnya {sangat memuaskan|memuaskan|baik}}."
  response = "{Terima kasih! Kami {berkomitmen|dedikasi|siap} untuk menyediakan layanan dan produk {berkualitas|yang berkualitas} untuk proyek Anda|Terima kasih! Kami {berkomitmen|siap|dedikasi} untuk memberikan layanan dan produk {berkualitas|yang berkualitas} untuk proyek Anda.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Fajar|Eko|Joko|Budi|Rudi|Agus|Hendra|Dedi|Samsul}"
  message = "{Saya {sangat puas|merasa puas|benar-benar puas} dengan hasil {pemasangan|instalasi} teralis dari teralis.bangunan.co. Rumah saya {sekarang|kini} {lebih aman|menjadi lebih aman|tampak lebih aman} dan {terlihat modern|berkesan modern|tampak modern}|Saya {sangat senang|sangat puas|benar-benar senang} dengan hasil {pemasangan|instalasi} teralis dari teralis.bangunan.co. Rumah saya {kini|sekarang} {lebih aman|tampak lebih aman|menjadi lebih aman} dan {terlihat modern|berkesan modern|tampak modern}}."
  response = "{Senang mendengar Anda {puas|senang|terkesan} dengan layanan kami. Terima kasih atas {kepercayaannya|kepercayaan Anda}!|Kami {senang|gembira} mendengar bahwa Anda {puas|senang|terkesan} dengan layanan kami. Terima kasih atas {kepercayaan|kepercayaan Anda}!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Ayu|Dewi|Lina|Maya|Putri|Ratna|Nina|Ika}"
  message = "{{Pelayanan|Layanan} teralis.bangunan.co {sangat memuaskan|benar-benar baik|memuaskan sekali}. Pagar besi yang saya pesan {sangat berkualitas|berkualitas tinggi|luar biasa} dan {sesuai|cocok} dengan {desain|model} yang saya {inginkan|harapkan|impikan}|Pelayanan dari teralis.bangunan.co {sangat memuaskan|benar-benar baik|memuaskan sekali}. Pagar besi yang saya pesan berkualitas tinggi dan {sesuai|cocok} dengan {desain|model} yang saya {impikan|harapkan|inginkan}}."
  response = "{Terima kasih! Kami {senang|gembira} dapat membantu mewujudkan {desain|model} yang Anda {impikan|inginkan} dengan pagar besi {berkualitas|yang berkualitas}|Terima kasih! Kami {senang|gembira} bisa membantu mewujudkan {desain|model} yang Anda {inginkan|harapkan} dengan pagar besi {berkualitas|yang berkualitas}}."
  rating = 4.6

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Budi|Andi|Rudi|Agus|Fajar|Dedi|Hendra|Samsul|Joko}"
  message = "{Teralis besi dari teralis.bangunan.co {sangat sesuai|cocok|tepat} untuk {melindungi|menjaga|merawat} jendela {rumah|hunian} saya. Proses pemasangan {cepat|lancar|efisien} dan {profesional|sangat profesional|berkualitas}|Teralis besi yang saya beli dari teralis.bangunan.co {sangat cocok|sangat sesuai|tepat} untuk {melindungi|menjaga|merawat} jendela {rumah|hunian} saya. Proses pemasangannya {cepat|lancar|efisien} dan {sangat profesional|profesional|berkualitas}}."
  response = "{Kami {senang|gembira|bahagia} mendengar bahwa Anda {puas|senang|terkesan} dengan produk kami. Terima kasih atas {ulasannya|feedbacknya|tanggapan Anda}!|Kami {sangat|amat} senang mendengar bahwa Anda {puas|senang|terkesan} dengan produk kami. Terima kasih untuk {ulasan positifnya|feedback positifnya|tanggapan baik Anda!}}"
  rating = 4.9

[[params.tabelItems]]
  name = "Teralis Jendela"
  price = "500.000 /unit"
[[params.tabelItems]]
  name = "Pagar Besi Minimalis"
  price = "600.000 /unit"
[[params.tabelItems]]
  name = "Pagar Besi Modern"
  price = "700.000 /unit"
[[params.tabelItems]]
  name = "Teralis Pintu"
  price = "400.000 /unit"
[[params.tabelItems]]
  name = "Pagar dan Teralis Custom"
  price = "650.000 /unit"

[params.appliList]
  "Teralis Jendela" = "jendela rumah, jendela kamar, jendela ruang tamu"
  "Pagar Besi Minimalis" = "pagar depan rumah, halaman depan, pekarangan"
  "Pagar Besi Modern" = "pagar rumah mewah, pagar minimalis modern"
  "Teralis Pintu" = "pintu rumah, pintu belakang, pintu samping"
  "Pagar dan Teralis Custom" = "desain khusus sesuai permintaan, ukuran dan bentuk sesuai pesanan"

[params.kegunaanList]
  "Teralis Jendela" = "memberikan keamanan pada jendela tanpa mengurangi estetika"
  "Pagar Besi Minimalis" = "melindungi properti dengan desain minimalis yang elegan"
  "Pagar Besi Modern" = "menambah nilai estetika dan keamanan pada rumah modern"
  "Teralis Pintu" = "meningkatkan keamanan pintu masuk rumah"
  "Pagar dan Teralis Custom" = "disesuaikan dengan kebutuhan dan preferensi desain pelanggan"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Layanan Pemasangan Teralis dan Pagar Besi | "
   highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"